version: 2.1
jobs:
  build:
    machine:
      enabled: true
      image: circleci/classic:201808-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build
          command: docker build -t themuse/terraform .
      - deploy:
          name: Push to dockerhub
          command: |
            if  [[ "$CIRCLE_BRANCH" == "master" ]]; then
                echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USERNAME --password-stdin
                docker push themuse/terraform:latest

                # Also tag by sha
                docker tag themuse/terraform:latest themuse/terraform:$CIRCLE_SHA1
                docker push themuse/terraform:$CIRCLE_SHA1

                # Finally, tag by version (<themuse version>-<terraform version>)
                version=1.1.0-0.12.9
                docker tag themuse/terraform:latest themuse/terraform:$version
                docker push themuse/terraform:$version
            fi
